# Generated by Django 5.2.6 on 2026-01-24 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("analysts", models.JSONField(blank=True, default=list, null=True)),
                (
                    "status_analysis",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("type", models.CharField(max_length=200)),
                ("context", models.TextField()),
                (
                    "workshop1_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "workshop2_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "workshop3_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "workshop4_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "workshop5_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
