# Generated by Django 5.2.6 on 2026-02-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysismodel",
            name="slug",
            field=models.SlugField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
