# Generated by Django 5.2.6 on 2026-03-07 23:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_analysismodel_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysismodel",
            name="executive_report",
            field=models.ImageField(
                blank=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="reports/",
            ),
        ),
        migrations.AddField(
            model_name="analysismodel",
            name="technical_report",
            field=models.ImageField(
                blank=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="reports/",
            ),
        ),
    ]
