apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: optirisk-backend-deploy
  namespace: argocd
spec:
  destination:
    namespace: optirisk
    server: https://kubernetes.default.svc
  project: optirisk
  source:
    helm:
      parameters:
        - name: image.repository
          value: lip13/optirisk
        - name: image.tag
          value: b1fd9bb324c650aef95cab8186f9b3ce8e2ec1ea
    path: helm/optirisk-backend-dev
    repoURL: https://github.com/Pauller13/optirisk.git
    targetRevision: helm-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
