apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: optirisk-backend-deploy
  namespace: argocd
spec:
  destination:
    namespace: optirisk
    server: https://kubernetes.default.svc
  project: optirisk
  source:
    helm:
      parameters:
        - name: image.repository
          value: lip13/optirisk
        - name: image.tag
          value: 08840ba452fc1f759cd7d72eea8d9e76abddf795
    path: helm/optirisk-backend-dev
    repoURL: https://github.com/Pauller13/optirisk.git
    targetRevision: helm-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
