# Generated by Django 5.2.6 on 2025-09-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customusermodel_slug_alter_customusermodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
