# Generated by Django 5.2.6 on 2025-09-21 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customusermodel_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=6, verbose_name='OTP Code')),
                ('type', models.CharField(choices=[('PASSWORD', 'PASSWORD'), ('TWO_FACTOR_AUTH', 'TWO_FACTOR_AUTH')], max_length=20, verbose_name='OTP Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
