# Generated by Django 5.2.6 on 2025-11-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_otpmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="secret_key",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
