# Generated by Django 5.2.6 on 2026-01-24 17:13

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_customusermodel_secret_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="user/",
            ),
        ),
    ]
