# Generated by Django 5.2.6 on 2026-03-03 23:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_customusermodel_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="https://res.cloudinary.com/dxb4y413d/image/upload/v1745187096/no-gender.jpg",
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="user/",
            ),
        ),
    ]
