# Generated by Django 5.2.6 on 2026-03-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_customusermodel_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="token_number",
            field=models.IntegerField(default=5),
        ),
    ]
