# Generated by Django 5.2.6 on 2026-03-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_customusermodel_token_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
