# Generated by Django 5.2.6 on 2026-03-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_customusermodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=100,
            ),
        ),
    ]
