# Generated by Django 5.2.6 on 2026-03-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_customusermodel_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("level", models.CharField(max_length=20)),
                ("action", models.CharField(max_length=20)),
                ("message", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
